config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :chirps
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "chirps#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chirp.rb
class Chirp < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :chirps
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chirps_controller.rb
class ChirpsController < ApplicationController
  before_action :set_chirp, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /chirps
  # GET /chirps.json
  def index
    @chirps = Chirp.all.order("created_at DESC")
    @chirp = Chirp.new
  end

  # GET /chirps/1
  # GET /chirps/1.json
  def show
  end

  # GET /chirps/new
  def new
    @chirp = current_user.chirps.build
  end

  # GET /chirps/1/edit
  def edit
  end

  # POST /chirps
  # POST /chirps.json
  def create
    @chirp = current_user.chirps.build(chirp_params)

    respond_to do |format|
      if @chirp.save
        format.html { redirect_to root_path, notice: 'chirp was successfully created.' }
        format.json { render :show, status: :created, location: @chirp }
      else
        format.html { render :new }
        format.json { render json: @chirp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chirps/1
  # PATCH/PUT /chirps/1.json
  def update
    respond_to do |format|
      if @chirp.update(chirp_params)
        format.html { redirect_to @chirp, notice: 'chirp was successfully updated.' }
        format.json { render :show, status: :ok, location: @chirp }
      else
        format.html { render :edit }
        format.json { render json: @chirp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chirps/1
  # DELETE /chirps/1.json
  def destroy
    @chirp.destroy
    respond_to do |format|
      format.html { redirect_to chirps_url, notice: 'chirp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chirp
      @chirp = Chirp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chirp_params
      params.require(:chirp).permit(:chirp)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def acount_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chirps_helper.rb
module ChirpsHelper
end

app/views/chirps/_chirp.html.erb
<div id="<%= dom_id chirp %>">
  <p>
    <strong>Chirp:</strong>
    <%= chirp.chirp %>
  </p>

</div>

app/views/chirps/_feed.html.erb
<div class="column is-half">
  <% if user_signed_in? %>
  <article class="media box">
    <figure class="media-left">
      <p class="image is-64x64">
        <img class="is-rounded" src="https://bulma.io/images/placeholders/64x64.png">%>
      </p>
    </figure>
    <div class="media-content">
       <%= render 'chirps/form' %>
    </div>
  </article>
  <% end %>


<% @chirps.each do | chirp | %>
  <div class="box">
    <article class="media">
      <div class="media-left">
        <figure class="image is-64x64">
        <img class="is-rounded" src="https://bulma.io/images/placeholders/64x64.png">%>
        </figure>
      </div>
      <div class="media-content">
        <div class="content">
          <strong><%= chirp.user.name %></strong><br />
          <small><%= chirp.user.username %></small><br/>
          <p><%= chirp.chirp %></p>
        </div>
        <% if user_signed_in? && current_user.id == chirp.user_id %>
        <nav class="level">
          <div class="level-left is-mobile">
            <%= link_to chirp, class: "level-item" do %>
              <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
            <% end %>
            <%= link_to edit_chirp_path(chirp), class: "level-item" do %>
              <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
            <% end %>
            <%= link_to chirp, method: :delete, data: { confirm: "Are you sure you want to delete this chirp?" } do %>
                <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
            <% end %>
          </div>
        </nav>
        <% end %>
      </div>
    </article>
  </div>
<% end %>
</div>

app/views/chirps/_follow-who.html.erb
<div class="column">
  <nav class="panel">
    <p class="panel-heading">Follow Suggestions</p>

    <div class="panel-block">
      <article class="media">
        <div class="media-left">
          <figure class="image is-32x32">
            <img class="is-rounded" src="https://bulma.io/images/placeholders/32x32.png">
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <p>
              <strong>Tambudzai Odilia</strong>
              <small>@tambudzai</small>
            </p>
          </div>
        </div>
      </article>
    </div>
    <div class="panel-block">
      <article class="media">
        <div class="media-left">
          <figure class="image is-32x32">
            <img class="is-rounded" src="https://bulma.io/images/placeholders/32x32.png">
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <p>
              <strong>Radha Dasoda-hae</strong>
              <small>@dasodamang</small>
            </p>
          </div>
        </div>
      </article>
    </div>
    <div class="panel-block">
      <article class="media">
        <div class="media-left">
          <figure class="image is-32x32">
            <img class="is-rounded" src="https://bulma.io/images/placeholders/32x32.png">
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <p>
              <strong>Paula Chimon</strong>
              <small>@paulaC101</small>
            </p>
          </div>
        </div>
      </article>
    </div>
  </nav>
</div>

app/views/chirps/_form.html.erb
<%= simple_form_for(@chirp) do |f| %>
<%= f.error_notification %>
<div class="field">
  <div class="control">
    <%= f.input :chirp, label: "chirp about it", input_html: { class: "textarea "}, wrapper: false, label_html: {class: "label"}, placeholder: "Compose a new chirp...", autofocus: true %>
  </div>
</div>
<%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/chirps/_profile.html.erb
<div class="column is-one-quarter">
  <nav class="panel">
    <p class="panel-heading">Profile</p>
    <div class="panel-block">
      <article class="media">
        <div class="media-left">
          <figure class="image is-64x64">
            <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <p>
              <strong><%= current_user.name %></strong><br />
              <small><%= current_user.username %></small>
            </p>
          </div>
        </div>
      </article>
    </div>
    <div class="panel-block">
      <div class="level is-mobile">
        <div class="level-item has-centered-text">
          <div>
            <p class="heading">Chirps</p>
            <p class="title is-6"><%= current_user.chirps.count %></p>
          </div>
        </div>
        <div class="level-item has-centered-text">
          <div>
            <p class="heading">Following</p>
            <p class="title is-6">145</p>
          </div>
        </div>
          <div class="level-item has-centered-text">
          <div>
            <p class="heading">Followers</p>
            <p class="title is-6">1023</p>
          </div>
        </div>
      </div>
    </div>
  </nav>
</div>

app/views/chirps/_trends.html.erb
<div class="column is-one-quarter">
  <nav class="panel">
    <p class="panel-heading">Trending</p>
    <a class="panel-block">
      Trend 1
    </a>
    <a class="panel-block">
      Trend 2
    </a>
    <a class="panel-block">
      Trend 3
    </a>
    <a class="panel-block">
      Trend 4
    </a>
    <a class="panel-block">
      Trend 5
    </a>
  </nav>
</div>

app/views/chirps/edit.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-half">
        <h1 class="title">Editing chirp</h1>
        <%= render 'form', chirp: @chirp %>
      </div>
    </div>
  </div>
</div>

<nav class="navbar is-fixed-bottom">
  <div class="navbar-menu">
    <div class="navbar-item">
      <div class="field is-grouped">
        <p class="control">
          <%= link_to 'Cancel', chirps_path, class: "button is-dark" %>
        </p>
    </div>
  </div>
</nav>

app/views/chirps/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <% if user_signed_in? %>
        <%= render 'profile' %>
      <% else %>
       <%= render 'trends' %>
      <% end %>

       <%= render 'feed' %>
       <%= render 'follow-who' %>
    </div>
  </div>
</section>

app/views/chirps/new.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-half">
        <h1 class="title">Create a new Chirp</h1>
          <%= render 'form', chirp: @chirp %>
      </div>
    </div>
  </div>
</div>

<nav class="navbar is-fixed-bottom">
  <div class="navbar-menu">
    <div class="navbar-item">
      <div class="field is-grouped">
        <p class="control">
          <%= link_to 'Cancel', chirps_path, class: "button is-dark" %>
        </p>
    </div>
  </div>
</nav>

app/views/chirps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Chirp:</strong>
  <%= @chirp.chirp %>
</p>

<%= link_to 'Edit', edit_chirp_path(@chirp) %> |
<%= link_to 'Back', chirps_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CHIRP (twitter clone)</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- font awesome kit-->
    <script src="https://kit.fontawesome.com/91be5eb45c.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notif">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>

    <nav class="navbar is-info">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-5">Chirp</h1>
        <% end %>

        <div class="navbar-burger burger" data-target="navbarExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <div id="navbarExample" class="navbar-menu">
        <div class="navbar-end">
          <div class="field is-grouped">
            <p class="control">
              <%= link_to 'New Chirp', new_chirp_path, class: "button is-info is-inverted" %>
            </p>
          </div>
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>